version: '3.8'

services:

  mysql:
    image: mysql:8.1
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root1234!
      MYSQL_DATABASE: grocery_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Backend456!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    working_dir: /backend
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: Backend456!
      DB_NAME: grocery_db
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    command: ["node", "index.js"]

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    working_dir: /frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

    

volumes:
  mysql_data:
